/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe: responde 200 si el proceso está vivo.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe — best-effort check de adapters críticos.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email + password → access + refresh tokens. */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh token → nuevo access token. */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario actual a partir del access token. */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout — en MVP no invalida tokens (stateless). */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List authorization cases
         * @description Lista paginada de casos visibles para el rol del usuario.
         *
         *     El rol se extrae del JWT (no del query string) para evitar escalada de
         *     privilegios — un hospital nunca puede pedir vista de auditor.
         */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        /**
         * Submit a new authorization case
         * @description Crea un caso de autorización y dispara el flow de decisión.
         *
         *     En MVP el flow MOCK (rule engine determinístico) corre síncrono y
         *     devuelve el caso decidido. En producción (B3) se devolvería 202 con
         *     `status=PENDIENTE` y la decisión llegaría por SSE.
         */
        post: operations["submit_case_api_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a new authorization case with a PDF report (multipart)
         * @description PDF upload variant of `POST /api/v1/cases`. Stores the file via FileStorage.
         */
        post: operations["submit_case_upload_api_v1_cases_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a case by id
         * @description Detalle de un caso. 404 si no existe.
         */
        get: operations["get_case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the agent trace for a case
         * @description Traza completa del agente para el caso. 404 si no existe.
         */
        get: operations["get_case_trace_api_v1_cases__case_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve an escalated case (auditor only)
         * @description El auditor cierra un caso escalado.
         *
         *     Solo accesible para `Role.AUDITOR`. La decisión queda registrada con
         *     `decided_by=AUDITOR`, `confidence=1.0`, `outcome=DECIDED`.
         */
        post: operations["resolve_case_api_v1_cases__case_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a file attached to a case (auth + RBAC)
         * @description Serves a stored PDF after RBAC + path-traversal checks.
         */
        get: operations["download_case_file_api_v1_cases__case_id__files__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extract/medical-report-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extraer campos del informe médico (PDF) para autocompletar el formulario */
        post: operations["extract_medical_report_pdf_api_v1_extract_medical_report_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extract/policy-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extraer campos de la póliza del paciente (PDF) para autocompletar el formulario */
        post: operations["extract_policy_pdf_api_v1_extract_policy_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List policies
         * @description Listado completo del catálogo de pólizas (read-only en MVP).
         */
        get: operations["list_policies_api_v1_policies_get"];
        put?: never;
        /** Create a policy (insurer-only) */
        post: operations["create_policy_api_v1_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a policy by number
         * @description Detalle de una póliza por su número. 404 si no existe.
         */
        get: operations["get_policy_api_v1_policies__number__get"];
        /** Update a policy by number (insurer-only) */
        put: operations["update_policy_api_v1_policies__number__put"];
        post?: never;
        /** Delete a policy by number (insurer-only) */
        delete: operations["delete_policy_api_v1_policies__number__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{number}/coverages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List coverages for a specific policy
         * @description Listado de coberturas de la póliza `number`.
         */
        get: operations["list_coverages_for_policy_api_v1_policies__number__coverages_get"];
        /** Replace all coverages for a policy (insurer-only) */
        put: operations["replace_coverages_api_v1_policies__number__coverages_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coverages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List coverages
         * @description Listado de coberturas. Si `policyNumber` viene, filtra por esa póliza.
         */
        get: operations["list_coverages_api_v1_coverages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insurers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List insurers
         * @description Listado del catálogo de aseguradoras.
         */
        get: operations["list_insurers_api_v1_insurers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard KPIs (insurer-only)
         * @description KPIs agregados para la vista de aseguradora.
         *
         *     Restringido a `Role.INSURER` — el hospital no necesita estos KPIs y el
         *     auditor tiene su propia bandeja de trabajo.
         */
        get: operations["get_dashboard_metrics_api_v1_dashboard_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procedures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or search procedures */
        get: operations["list_procedures_api_v1_procedures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or search patients */
        get: operations["list_patients_api_v1_patients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single patient by id */
        get: operations["get_patient_api_v1_patients__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_extract_medical_report_pdf_api_v1_extract_medical_report_pdf_post */
        Body_extract_medical_report_pdf_api_v1_extract_medical_report_pdf_post: {
            /**
             * File
             * @description PDF del informe médico (hospital)
             */
            file: string;
        };
        /** Body_extract_policy_pdf_api_v1_extract_policy_pdf_post */
        Body_extract_policy_pdf_api_v1_extract_policy_pdf_post: {
            /**
             * File
             * @description PDF de póliza / certificado aseguradora
             */
            file: string;
        };
        /** Body_submit_case_upload_api_v1_cases_upload_post */
        Body_submit_case_upload_api_v1_cases_upload_post: {
            /** Policy Number */
            policy_number: string;
            /** Patient Id */
            patient_id: string;
            /** File */
            file: string;
            /** Procedure Solicited Hint */
            procedure_solicited_hint?: string | null;
            /** Diagnosis */
            diagnosis?: string | null;
            /** Attending Doctor */
            attending_doctor?: string | null;
            /** Scenario Key */
            scenario_key?: string | null;
        };
        /**
         * CaseLinks
         * @description HATEOAS-lite — paths relativos para el cliente.
         */
        CaseLinks: {
            /** Self */
            self: string;
            /** Trace */
            trace: string;
            /** Resolve */
            resolve?: string | null;
            /** Events */
            events: string;
        };
        /**
         * CaseOut
         * @description Caso de autorización — respuesta canónica del API.
         */
        CaseOut: {
            /** Id */
            id: string;
            status: components["schemas"]["CaseStatus"];
            /** Reportid */
            reportId: string;
            /** Policynumber */
            policyNumber: string;
            decision?: components["schemas"]["DecisionOut"] | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Decidedat */
            decidedAt?: string | null;
            _links: components["schemas"]["CaseLinks"];
        };
        /**
         * CaseStatus
         * @description CaseStatus — estado del workflow del caso (dashboard).
         * @enum {string}
         */
        CaseStatus: "PENDIENTE" | "APROBADO_AUTO" | "DOCS_PEDIDOS" | "ESCALADO" | "DECIDIDO";
        /**
         * CaseSubmitIn
         * @description Body de `POST /api/v1/cases` — pedir autorización.
         */
        CaseSubmitIn: {
            report: components["schemas"]["MedicalReportIn"];
            /**
             * Policynumber
             * @description Número de la póliza del paciente.
             */
            policyNumber: string;
            /**
             * Scenariokey
             * @description Override opcional para forzar un escenario en demos.
             */
            scenarioKey?: string | null;
        };
        /**
         * CaseTraceOut
         * @description Wrapper para `GET /api/v1/cases/{id}/trace`.
         */
        CaseTraceOut: {
            /** Trace */
            trace: components["schemas"]["TraceStepOut"][];
        };
        /**
         * CoverageIn
         * @description Item de PUT /policies/{number}/coverages.
         */
        CoverageIn: {
            /** Policynumber */
            policyNumber: string;
            /** Procedurecode */
            procedureCode: string;
            /** Covered */
            covered: boolean;
            /** Waitingdays */
            waitingDays: number;
            /** Copay */
            copay: number | string;
            /** Requireddocs */
            requiredDocs?: string[];
        };
        /**
         * CoverageOut
         * @description Cobertura — DTO de salida.
         *
         *     `copay` se serializa como `Decimal` → string en JSON (Pydantic v2 default
         *     para `Decimal`); el frontend ya lo parsea como string monetaria.
         */
        CoverageOut: {
            /** Policynumber */
            policyNumber: string;
            /** Procedurecode */
            procedureCode: string;
            /** Covered */
            covered: boolean;
            /** Waitingdays */
            waitingDays: number;
            /** Copay */
            copay: string;
            /** Requireddocs */
            requiredDocs?: string[];
        };
        /**
         * DashboardMetricsOut
         * @description KPIs agregados — DTO de salida para `GET /api/v1/dashboard/metrics`.
         */
        DashboardMetricsOut: {
            /** Total */
            total: number;
            /** Autoapproved */
            autoApproved: number;
            /** Docsrequested */
            docsRequested: number;
            /** Escalated */
            escalated: number;
            /** Decided */
            decided: number;
            /** Autoapprovedpct */
            autoApprovedPct: number;
            /** Avgconfidence */
            avgConfidence: number;
            /** Avgdurationms */
            avgDurationMs: number;
        };
        /**
         * DecidedBy
         * @description DecidedBy — quién emitió la decisión.
         * @enum {string}
         */
        DecidedBy: "agent" | "auditor";
        /**
         * DecisionOut
         * @description Decisión emitida por el agente o el auditor.
         */
        DecisionOut: {
            outcome: components["schemas"]["Outcome"];
            /** Rationale */
            rationale: string;
            /** Confidence */
            confidence: number;
            decidedBy: components["schemas"]["DecidedBy"];
            /** Evidence */
            evidence?: components["schemas"]["EvidenceOut"][];
            /** Missingdocs */
            missingDocs?: string[];
            escalationReason?: components["schemas"]["EscalationReason"] | null;
            /** Modelused */
            modelUsed?: string | null;
        };
        /**
         * EscalationReason
         * @description EscalationReason — motivos de escalamiento a auditor humano.
         * @enum {string}
         */
        EscalationReason: "WAITING_PERIOD_NOT_MET" | "LOW_CONFIDENCE_PROCEDURE_MATCH" | "PDF_EXTRACTION_FAILURE" | "PROCEDURE_NOT_COVERED" | "POLICY_INACTIVE" | "PROCEDURE_NOT_MATCHED" | "EXTRACTION_FAILED" | "LOW_CONFIDENCE" | "UNEXPECTED_ERROR";
        /**
         * EvidenceOut
         * @description Cita auditable que respalda la decisión.
         */
        EvidenceOut: {
            source: components["schemas"]["EvidenceSource"];
            /** Field */
            field: string;
            /** Quote */
            quote: string;
        };
        /**
         * EvidenceSource
         * @description EvidenceSource — origen de la cita.
         * @enum {string}
         */
        EvidenceSource: "report" | "policy";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InsurerOut
         * @description Aseguradora — DTO de salida.
         */
        InsurerOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
        };
        /**
         * LoginRequest
         * @description Body de `POST /auth/login`.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Respuesta de `POST /auth/login`.
         */
        LoginResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
            /**
             * Tokentype
             * @default bearer
             */
            tokenType: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * MedicalPdfExtractOut
         * @description Campos típicos del informe médico (plantilla `docs/informe-medico-template.md`).
         */
        MedicalPdfExtractOut: {
            /**
             * Patient Id
             * @description ID o número de historia del paciente si aparece.
             */
            patient_id?: string | null;
            /**
             * Policy Number
             * @description Número de póliza si consta en el informe.
             */
            policy_number?: string | null;
            /**
             * Attending Doctor
             * @description Médico tratante.
             */
            attending_doctor?: string | null;
            /**
             * Diagnosis
             * @description Diagnóstico principal en texto.
             */
            diagnosis?: string | null;
            /**
             * Diagnosis Code
             * @description CIE-10 del diagnóstico principal.
             */
            diagnosis_code?: string | null;
            /**
             * Procedure Code
             * @description CIE-10 del procedimiento solicitado, si aplica.
             */
            procedure_code?: string | null;
            /**
             * Procedure Name
             * @description Nombre del procedimiento propuesto.
             */
            procedure_name?: string | null;
            /**
             * Report Text Summary
             * @description Resumen breve o primeros párrafos citables del informe (opcional).
             */
            report_text_summary?: string | null;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /**
         * MedicalReportIn
         * @description Informe médico que el hospital adjunta al crear un caso.
         */
        MedicalReportIn: {
            /**
             * Patientid
             * @description ID del paciente (Pacientes:id).
             */
            patientId: string;
            /** @default text */
            format: components["schemas"]["ReportFormat"];
            /**
             * Content
             * @description Contenido del informe (texto o ruta del PDF).
             */
            content: string;
            /**
             * Proceduresolicitedhint
             * @description Procedimiento sugerido por el hospital (código o descripción).
             */
            procedureSolicitedHint?: string | null;
            /** Diagnosis */
            diagnosis?: string | null;
            /** Attendingdoctor */
            attendingDoctor?: string | null;
        };
        /**
         * Outcome
         * @description Outcome — resultado emitido por el agente o el auditor.
         * @enum {string}
         */
        Outcome: "APPROVED_AUTO" | "DOCS_REQUESTED" | "ESCALATED" | "DECIDED" | "PENDING";
        /** PatientOut */
        PatientOut: {
            /** Id */
            id: string;
            /** Dni */
            dni: string;
            /** Name */
            name: string;
            /**
             * Dob
             * Format: date
             */
            dob: string;
            /** Sex */
            sex: string;
        };
        /**
         * PolicyIn
         * @description Body de POST/PUT /policies.
         */
        PolicyIn: {
            /** Number */
            number: string;
            /** Patientid */
            patientId: string;
            /** Plan */
            plan: string;
            /** Insurerid */
            insurerId: string;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Enddate
             * Format: date
             */
            endDate: string;
            status: components["schemas"]["PolicyStatus"];
        };
        /**
         * PolicyOut
         * @description Póliza — DTO de salida.
         */
        PolicyOut: {
            /** Number */
            number: string;
            /** Patientid */
            patientId: string;
            /** Plan */
            plan: string;
            /** Insurerid */
            insurerId: string;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Enddate
             * Format: date
             */
            endDate: string;
            status: components["schemas"]["PolicyStatus"];
        };
        /**
         * PolicyPdfExtractOut
         * @description Campos típicos de la póliza (plantilla `docs/poliza-paciente-template.md`).
         */
        PolicyPdfExtractOut: {
            /**
             * Policy Number
             * @description Número de póliza.
             */
            policy_number?: string | null;
            /**
             * Patient Id
             * @description Identificación del paciente cubierto si aparece (cédula, ID interno, etc.).
             */
            patient_id?: string | null;
            /**
             * Insurer Name
             * @description Nombre de la aseguradora.
             */
            insurer_name?: string | null;
            /**
             * Plan Name
             * @description Plan o producto.
             */
            plan_name?: string | null;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /**
         * PolicyStatus
         * @description PolicyStatus — estado canónico de una póliza.
         * @enum {string}
         */
        PolicyStatus: "ACTIVE" | "INACTIVE" | "SUSPENDED";
        /** ProcedureOut */
        ProcedureOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Waitingdaystypical */
            waitingDaysTypical?: number | null;
        };
        /**
         * RefreshRequest
         * @description Body de `POST /auth/refresh`.
         */
        RefreshRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /**
         * RefreshResponse
         * @description Respuesta de `POST /auth/refresh`.
         */
        RefreshResponse: {
            /** Accesstoken */
            accessToken: string;
            /**
             * Tokentype
             * @default bearer
             */
            tokenType: string;
        };
        /**
         * ReportFormat
         * @description ReportFormat — formato del informe médico.
         * @enum {string}
         */
        ReportFormat: "text" | "pdf";
        /**
         * ResolveCaseIn
         * @description Body de `POST /api/v1/cases/{id}/resolve` — auditor cierra el caso.
         */
        ResolveCaseIn: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "APPROVED" | "REJECTED";
            /**
             * Message
             * @description Mensaje humano final que verá el hospital.
             */
            message: string;
            /**
             * Reasoning
             * @description Razonamiento del auditor (rationale).
             */
            reasoning: string;
        };
        /**
         * Role
         * @description Rol del usuario (PRD §3 — 3 roles del MVP).
         * @enum {string}
         */
        Role: "hospital" | "insurer" | "auditor";
        /**
         * TraceStepOut
         * @description Paso individual de la traza del agente.
         */
        TraceStepOut: {
            /** Node */
            node: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            state: components["schemas"]["TraceStepState"];
            /** Durationms */
            durationMs?: number | null;
            /** Modelused */
            modelUsed?: string | null;
            /** Tokensin */
            tokensIn?: number | null;
            /** Tokensout */
            tokensOut?: number | null;
            /** Detail */
            detail?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * TraceStepState
         * @description TraceStepState — estado terminal o en progreso de un paso de traza.
         * @enum {string}
         */
        TraceStepState: "running" | "done" | "error";
        /**
         * UserOut
         * @description Representación pública de un usuario (sin hash).
         */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                /** @description Filtro por status del caso. */
                status?: components["schemas"]["CaseStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_case_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseSubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_case_upload_api_v1_cases_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_case_upload_api_v1_cases_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_trace_api_v1_cases__case_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseTraceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_case_api_v1_cases__case_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveCaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_case_file_api_v1_cases__case_id__files__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_medical_report_pdf_api_v1_extract_medical_report_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_medical_report_pdf_api_v1_extract_medical_report_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicalPdfExtractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_policy_pdf_api_v1_extract_policy_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_policy_pdf_api_v1_extract_policy_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyPdfExtractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_api_v1_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"][];
                };
            };
        };
    };
    create_policy_api_v1_policies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_api_v1_policies__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_policy_api_v1_policies__number__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_policy_api_v1_policies__number__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_coverages_for_policy_api_v1_policies__number__coverages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_coverages_api_v1_policies__number__coverages_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverageIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_coverages_api_v1_coverages_get: {
        parameters: {
            query?: {
                /** @description Filtro opcional por número de póliza. */
                policyNumber?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insurers_api_v1_insurers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsurerOut"][];
                };
            };
        };
    };
    get_dashboard_metrics_api_v1_dashboard_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardMetricsOut"];
                };
            };
        };
    };
    list_procedures_api_v1_procedures_get: {
        parameters: {
            query?: {
                /** @description Substring filter by code or name. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcedureOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patients_api_v1_patients_get: {
        parameters: {
            query?: {
                /** @description Filtra por DNI exacto (devuelve 0 ó 1). */
                dni?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"][];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_api_v1_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Patient not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
